name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Check out submodules
      run: git submodule update --init
    - name: Build for yggdrasil
      run: make DEVICE=yggdrasil -j$(nproc --all)
    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: device-cpio
        path: out/*
        if-no-files-found: error
